// Importing necessary modules
const User = require('../models/userData'); // User model for interacting with the user data in the database
const mongoose = require('mongoose'); // Mongoose for handling MongoDB operations
const bcrypt = require('bcrypt'); // Bcrypt for comparing hashed passwords
const jwt = require('jsonwebtoken'); // JWT for generating and verifying tokens

// JSON WEB TOKENS explanation:
// JSON Web Tokens (JWT) have 3 components:
// 1. Header: Contains the algorithm used for signing the token.
// 2. Payload: Contains the data (e.g., user email) to be transferred in the token.
// 3. Signature: Used to verify the authenticity of the token. It is generated by signing the header and payload using a secret key.

const generateTokens = (email) => {
    // Function to generate JWT for login and signup. The token is signed with the user's email and expires in 3 days.
    return jwt.sign({email}, process.env.SYM_KEY, {expiresIn: '3d'});
}

// Login function for authenticating users
const loginRequest = async (req, res) => {
    const {email, password} = req.body; // Destructuring email and password from the request body

    // Logging the email and password received in the request for debugging purposes
    console.log(`Login attempt with Email: ${email} and Password: ${password}`);

    let errorFields = []; // Initialize an array to store any errors related to missing fields
    if (!email) {
        errorFields.push('Email'); // If email is missing, add it to error fields
    }
    if (!password) {
        errorFields.push('Password'); // If password is missing, add it to error fields
    }
    if (errorFields.length != 0) {
        // If there are missing fields, return an error response with the list of fields
        return res.status(400).json({error: 'Please fill out all the fields', errorFields});
    }

    try {
        const user = await User.findOne({ email }); // Find user by email in the database

        // Log the user details retrieved from the database for debugging purposes
        if (user) {
            console.log(`User found in database: ${JSON.stringify(user, null, 2)}`);
        } else {
            console.log('No user found with the provided email');
        }

        if (!user) {
            errorFields.push('Email');
            return res.status(400).json({error: 'Incorrect email', errorFields}); // Return error if user is not found
        }

        // Log the comparison between input password and stored hashed password
        console.log(`Comparing input password: ${password} with hashed password: ${user.password}`);

        // Compare the input password with the stored hashed password using bcrypt
        const compare = await bcrypt.compare(password, user.password);
        
        if (compare) {
            // If password matches, generate a token and return user details and token in the response
            const userToken = generateTokens(user.email);
            console.log('Password match. Generating token and logging in.');
            res.status(200).json({email, occupation: user.occupation, fname: user.fname, userToken});
        } else {
            errorFields.push('Password');
            console.log('Password mismatch.');
            res.status(400).json({error: 'Incorrect password', errorFields}); // Return error if passwords do not match
        }
    } catch (error) {
        console.log('Error during login:', error.message); // Log any errors that occur during login
        res.status(400).json({error: error.message}); // Return the error message if an error occurs during login
    }
};

module.exports = {
    loginRequest // Exporting loginRequest function for use in routes
}
